services:
  scheduler:
    build: .
    container_name: scheduler
    develop:
      watch:
        - action: sync+restart
          path: ./
          target: /app
          ignore:
            - .gitignore
            - bin/
